GET http://localhost:5115/api/auth
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjA4ZGUwZDk5LTQ3MGMtNDU0ZC04MWUzLTE5NTc1NjVmMWI1YyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJtaWxsem8iLCJleHAiOjE3NjEwNzUyODgsImlzcyI6Ik1lZGlhIEJyb3dzZXIiLCJhdWQiOiJNZWRpYSBCcm93c2VyIEF1ZGllbmNlIn0.TVu-IjrLGbU4RJ_9cpjAri0dXI5oalrGRLq4NKIIUc8AhtdlS7qYqgDtUYUq0-KDKiIbPEzB0FvLsEr9C1-2EA
Accept: application/json